### ISSUE TITLE
Oracle add duplicate slashes for ClassType of ObjectIdentity in ACL provider

### ISSUE THREAD

**Issue by soyuka** [symfony/security-acl#11]
https://github.com/symfony/symfony/issues/15723 follow up

Indeed, when [`$this->connection->quote` is used on the `classType`](https://github.com/symfony/security-acl/blob/2b22539c83027c24e06bac933a8d586e683ca335/Dbal/MutableAclProvider.php#L505), Oracle adds two back-slashes.

I've found a simple fix that is to `stripcslashes($classType)` on [hydrateObjectIdentities](https://github.com/symfony/security-acl/blob/2b22539c83027c24e06bac933a8d586e683ca335/Dbal/AclProvider.php#L536). But this should only apply when the `$classType` contains more than one `\`.

Thoughts?

**Comment by derrabus** [comment]
@soyuka If you're still around (2015, wow), can you have a look at #96?

**Comment by soyuka** [comment]
Hi @derrabus, yes around but not using Oracle anymore the fix looks alright though :)

**Comment by FaritSlv** [comment]
Hi @derrabus, will you accept the PR? :)

**Comment by derrabus** [comment]
It looks good, but I don't have a setup to verify it. 🤔

**Comment by FaritSlv** [comment]
@derrabus 
Here is the docker image of OracleDB that I am using
`container-registry.oracle.com/database/express:latest`

The rest is standard.

**Comment by FaritSlv** [comment]
@derrabus 
Hi, is there anything required of me to accept a PR?

**Comment by derrabus** [comment]
My main issue is that we don't have a maintainer with Oracle knowledge or a CI that runs tests against Oracle on this repo. I don't feel like I'm the right person to merge this.

**Comment by FaritSlv** [comment]
Hi @derrabus
If I write tests and CI for Oracle DB it will somehow help?

**Comment by wouterj** [comment]
It would be great if we can refactor https://github.com/symfony/security-acl/blob/main/Tests/Dbal/AclProviderTest.php to test on Oracle, MySQL and sqlite (current) on GitHub actions (and skip the particular database if any of them is not supported locally).

That would give us much more confidence that the fix works and we're not breaking it in the future.

**Comment by soyuka** [comment]
testing on oracle is really hard as you need EULA to be accepted before running their dev tools ask @greg0ire I think he managed to but not sure he took much more time

**Comment by greg0ire** [comment]
I tried to do so on the ORM, since we already do have Oracle test on the DBAL. My attempt can be seen at https://github.com/doctrine/orm/pull/8958

**Comment by wouterj** [comment]
Hmm, that's a bit of a bummer...

In that case, we rely on the community. Currently, https://github.com/symfony/security-acl/pull/96 is open without any reviewers. If anyone that has Oracle locally can verify this indeed fixes this annoying bug, I would be much more confident when merging the PR.
