### ISSUE TITLE
Will security-core 6 series be supported?

### ISSUE THREAD

**Issue by smith-30** [symfony/security-acl#118]
### AsIs

The following depended on interfaces that will be removed in security-core 6.
This will likely result in an error when used with symfony 6.
https://github.com/symfony/security-acl/blob/main/Domain/SecurityIdentityRetrievalStrategy.php#L85

### Want

Change the processing of the relevant line appropriately to make it work with security-core version 6.

### Misc

I saw this issue, but I couldn't figure out what to do with AuthenticationTrustResolverInterface::isAnonymous().
https://github.com/symfony/security-acl/issues/99

**Comment by wouterj** [comment]
That call is only used on <6.0 for the reasons you mentioned.

Did you experience any issue while using this package with Symfony 6? Both 6 and 7 should be supported.
