### ISSUE TITLE
2.8 and 3.0 releases for security-acl?

### ISSUE THREAD

**Issue by weaverryan** [symfony/security-acl#14]
Hi guys!

We've extracted this from the core, will there be a release? I haven't followed the issue tracker closely, are we still pending items that need to be done?

Thans!

**Comment by fabpot** [comment]
#3

**Comment by Tobion** [comment]
As a reminder, 2.7 should be merged upwards.

**Comment by xabbuh** [comment]
@fabpot #3 has been merged

**Comment by XWB** [comment]
Ping @fabpot

**Comment by Id4v** [comment]
Any news about this?

**Comment by fabpot** [comment]
I've just released 2.8.0 and 3.0.0.

**Comment by francoispluchino** [comment]
@fabpot Thanks!
