### ISSUE TITLE
Missing .travis.yml

### ISSUE THREAD

**Issue by linaori** [symfony/security-acl#2]
@nicolas-grekas Do you happen to have a `.travis.yml` up your sleeve which you can add here?

I will also need one for [symfony/AclBundle](https://github.com/symfony/AclBundle) if you happen to have a copy/paste ready.

/cc @fabpot can you this repository and `symfony/AclBundle` to Travis?

https://github.com/symfony/AclBundle/pull/1 has a todo for travis as well.

**Comment by fabpot** [comment]
I"ve just enabled Travis for this repo.
