### ISSUE TITLE
Why doesn't doctrine fixture bundle truncate symfony ACL tables?

### ISSUE THREAD

**Issue by Redigast13** [symfony/security-acl#21]
I use symfony this with doctrine fixtures bundle. I created acl tables using php bin/console init:acl command, also I could created them using php bin/console doctrine:schema:update --force command.

I load fixtures using php bin/console doctrine:fixtures:load command. If I use this command it truncates all tables except the acl_* tables (acl_classes, acl_entries, acl_object_identities, acl_object_identity_ancestors, acl_security_identities) before executing. Why does it happen and how to make this command to truncate all DB tables?

**Comment by xabbuh** [comment]
I fail to see how this is related to the ACL package as the `doctrine:fixtures:load` command is part of the DoctrineFixturesBundle.
