### ISSUE TITLE
The command "init:acl" doesn't work for me.

### ISSUE THREAD

**Issue by xiranst** [symfony/security-acl#25]
I use the latest version of symfony: 3.0+, when i tried to enable the acl on my project, but i got the error message:
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "init" namespace. 

i checked the security-acl has been installed into my project and run composer update command. 
it is still.

so, what's happened?

**Comment by stof** [comment]
have you registered SecurityBundle in your kernel ?

**Comment by xiranst** [comment]
@stof yes. the SecurityBundle is registered in kernel default.
new Symfony\Bundle\SecurityBundle\SecurityBundle(),

**Comment by xiranst** [comment]
working now.
i made a mistake that is the configuration of acl not correct.
