### ISSUE TITLE
Symfony 4 compatibility

### ISSUE THREAD

**Issue by yurtesen** [symfony/security-acl#34]
Will you make a 4.x release to update `composer.json` so this can be installed with symfony 4?

**Comment by xabbuh** [comment]
The Acl component does not attract much attention nowadays. Would you like to open a PR?

**Comment by yurtesen** [comment]
I really do not need the ACL component. But this currently stops me from using Sonata Admin with Symphony 4.
See: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/771

**Comment by jaikdean** [comment]
The latest `master` already allows Symfony 4 in `composer.json` and the unit tests all pass when using the latest stable versions.

**Comment by jaikdean** [comment]
@fabpot ?

**Comment by jaikdean** [comment]
This has been fixed by v3.0.1. Thanks Fabien!
