### ISSUE TITLE
BC break with Doctrine DBAL 2.9.0

### ISSUE THREAD

**Issue by sandermarechal** [symfony/security-acl#43]
Symfony ACL defines its Schema with the option `"autoincrement" => "auto"` on all ID columns. But "autoincrement" is a boolean option, taking only true/false. Doctrine DBAL 2.9.0 uses stricter type checking (i.e. === instead of ==). This causes the schema diff function to always generate a diff for all ACL "id" columns, because `"auto" !== true`.

Basically, schema migrations are now broken for any version of Symfony ACL in combination with DBAL 2.9.0.

See also doctrine/dbal#3389

**Comment by chalasr** [comment]
The option has always been [documented as a boolean](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/schema-representation.html#portable-options), same for the dbal `Column::$_autoincrement` property. We should change `auto` to `true` as a bugfix to me

**Comment by sandermarechal** [comment]
Yes we should. But that does leave the problem that all released versions have version constraints that allow DBAL 2.9.0 but still use "auto". Hopefully DBAL can fix that on their end.
