### ISSUE TITLE
PHP 5.5 compatibility

### ISSUE THREAD

**Issue by remicollet** [symfony/security-acl#52]
According to composer.json, this package is compatible with 5.5.9+

But 744c6d5b56ef1dc2d6f8018291b5a5ca1dc48ae5 introduce 7.1+ code

Running test suite with 5.6
`PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /builddir/build/BUILDROOT/php-symfony-security-acl-3.0.3-1.el7.remi.x86_64/usr/share/php/Symfony/Component/Security/Acl/Domain/SecurityIdentityRetrievalStrategy.php on line 88`

**Comment by nicolas-grekas** [comment]
Fixed in #51 / v3.0.4
Thanks for the report.
