### ISSUE TITLE
doctrine/common 3 support

### ISSUE THREAD

**Issue by jaikdean** [symfony/security-acl#57]
There is a dev requirement for `doctrine/common:~2.2`, so tests pass correctly. However, there is no non-dev requirement or conflict with `doctrine/common:~3.0`, so this package can be installed alongside an incompatible version.

This appeared while adding `doctrine/common:~3.0` support to `sonata-project/admin-bundle` (see https://github.com/sonata-project/SonataAdminBundle/pull/6127) as there are errors in tests as follows:

```
Error: Interface 'Doctrine\Common\NotifyPropertyChanged' not found
/home/travis/build/sonata-project/SonataAdminBundle/vendor/symfony/security-acl/Domain/Acl.php:36
…
```

**Comment by fabpot** [comment]
Someone will need to work on compatibility. Are you willing to help?

**Comment by jaikdean** [comment]
@fabpot I'll work on it.

**Comment by jordisala1991** [comment]
There are already 2 PRs about that on this package, maybe you can start based on that work @jaikdean

**Comment by jaikdean** [comment]
The existing PRs are #53 and #54.

**Comment by jordisala1991** [comment]
I think we still missing 3.0 in doctrine common for require/dev . IMO it is not blocking for us now, because this package is not blocking the install of 3.0 but will be nice to add it.

**Comment by rickpelletier** [comment]
I think this problem also exists with the combination of doctrine/common:~2.2 and symfony/security-acl:~3.0.

When I ran an install today, composer did not see any problems and went ahead and bumped symfony/security-acl from 3.0.4 to 3.1.0, but kept doctrine/common to 2.8.1 and did not install any version of doctrine/persistence, resulting in this same error.

I'm a little confused as to why the doctrine dependencies are in the dev section of the composer.json - should they perhaps be in the main section?
