### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by fabpot** [symfony/security-acl#59]
If someone wants to help, one can help update the tests to modern PHPUnit. Right now, we still have some `getMock()` calls, and tests with no assertions.

**Comment by thamerbelfkihthamer** [comment]
@fabpot  this one is still valid?

**Comment by OskarStark** [comment]
As [this](https://github.com/symfony/security-acl/pull/61) is not merged yet, I would say yes

**Comment by acrobat** [comment]
I've started a new PR #66 that fixes this issue and adds a github actions setup so that new PR's will be tested before merging.
