### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by derrabus** [symfony/security-acl#99]
Tests on the main branch currently fail with Symfony 6:

* `AuthenticationTrustResolverInterface::isAnonymous()` is called, but that class has been removed in Symfony 6.
* Some tests use the `AnonymousToken` class which has also been removed.
* The constant `AuthenticatedVoter::IS_AUTHENTICATED_ANONYMOUSLY` is accessed. Gone as well.

**Comment by wouterj** [comment]
I can look at these wednesday afternoon if you want.

**Comment by acrobat** [comment]
I've made a start in #100, I look further into this in the next few days.

**Comment by jordisala1991** [comment]
Since the failing tests are now fixed, can you do a new release of Symfony ACL component?

Thank you! 🙏

**Comment by wouterj** [comment]
Yes, we are preparing a release of this package shortly

**Comment by derrabus** [comment]
If you're eagerly waiting for that release, please don't hesitate to test your projects with the current main branch. We're happy about any feedback we can gather _before_ the actual release.

**Comment by jordisala1991** [comment]
SonataAdminBundle (and all related bundles) is being tested against this component main branch since we added Symfony 6.0 support. No breaks so far (I guess we don't have the ACL part perfectly covered by tests, but still)

**Comment by wouterj** [comment]
Just published a release for this package: https://github.com/symfony/security-acl/releases/tag/v3.3.0
